(() => {
    'use strict';
    if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',loadDashboard);else loadDashboard();

    async function loadDashboard(){
        const now=new Date(),monthName=now.toLocaleDateString(undefined,{month:'long'});
        document.getElementById('dashboardDate').textContent=now.toLocaleDateString(undefined,{weekday:'long',day:'numeric',month:'long',year:'numeric'});
        document.getElementById('birthdayMonthLabel').textContent=monthName;
        document.getElementById('anniversaryMonthLabel').textContent=monthName;
        try{
            const [employees,cards]=await Promise.all([HRCanvasAPI.listEmployees(),HRCanvasAPI.listCards()]);
            const dates=employees.map(employee=>({dob:parseEmployeeDate(employee.dob),doj:parseEmployeeDate(employee.doj)}));
            const todayBirthdays=dates.filter(item=>item.dob&&item.dob.getMonth()===now.getMonth()&&item.dob.getDate()===now.getDate()).length;
            const monthBirthdays=dates.filter(item=>item.dob&&item.dob.getMonth()===now.getMonth()).length;
            const monthAnniversaries=dates.filter(item=>item.doj&&item.doj.getMonth()===now.getMonth()&&now.getFullYear()-item.doj.getFullYear()>0).length;
            setCount('addedEmployees',employees.length);setCount('todayBirthdays',todayBirthdays);setCount('monthBirthdays',monthBirthdays);setCount('monthAnniversaries',monthAnniversaries);
            const missingPhotos=employees.filter(employee=>!employee.photo).sort((a,b)=>a.fullName.localeCompare(b.fullName));renderMissingPhotos(missingPhotos);
            renderCreatedCards(cards.sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt))));
        }catch(error){const notice=document.getElementById('dashboardNotice');notice.hidden=false;notice.textContent=`Dashboard data could not be loaded: ${error.message}`;}
    }

    function setCount(id,value){document.getElementById(id).textContent=Number(value).toLocaleString();}
    function renderMissingPhotos(employees){const list=document.getElementById('missingPhotoList'),empty=document.getElementById('missingPhotoEmpty');document.getElementById('missingPhotoCount').textContent=employees.length;list.replaceChildren();employees.forEach(employee=>{const row=document.createElement('article');row.className='missing-photo-row';const avatar=document.createElement('div');avatar.className='missing-photo-avatar';const icon=document.createElement('img');icon.src='assets/icons/user.svg';icon.alt='';avatar.appendChild(icon);const person=document.createElement('div');person.className='missing-photo-person';const name=document.createElement('strong');name.textContent=employee.fullName;const details=document.createElement('small');details.textContent=`${employee.id} · ${employee.location||'Location not set'}`;person.append(name,details);const upload=document.createElement('a');upload.className='missing-photo-upload';upload.href=`pages/employees.html?employee=${encodeURIComponent(employee.id)}`;upload.textContent='Upload';upload.setAttribute('aria-label',`Upload photo for ${employee.fullName}`);row.append(avatar,person,upload);list.appendChild(row);});empty.hidden=employees.length>0;}
    function renderCreatedCards(cards){const viewport=document.getElementById('createdCardsViewport'),track=document.getElementById('createdCardsTrack'),empty=document.getElementById('createdCardsEmpty'),dots=document.getElementById('createdCardsDots'),previous=document.getElementById('cardsPrevious'),next=document.getElementById('cardsNext');track.replaceChildren();dots.replaceChildren();const older=cards.slice(1),leftCount=Math.ceil(older.length/2),ordered=cards.length?[...older.slice(0,leftCount).reverse(),cards[0],...older.slice(leftCount)]:[],latestIndex=leftCount;ordered.forEach((card,index)=>{const item=document.createElement('a'),image=document.createElement('img'),name=document.createElement('span'),dot=document.createElement('i');item.className='carousel-card';item.href='pages/birthday-cards.html';item.dataset.index=index;image.src=card.url;image.alt=`Birthday card for ${card.fullName}`;name.textContent=card.fullName;item.append(image,name);track.appendChild(item);dots.appendChild(dot);});empty.hidden=cards.length>0;viewport.hidden=cards.length===0;previous.disabled=cards.length<2;next.disabled=cards.length<2;if(!cards.length)return;const items=[...track.children],dotItems=[...dots.children];let frame;const markCentered=()=>{const center=viewport.getBoundingClientRect().left+viewport.clientWidth/2;let active=0,distance=Infinity;items.forEach((item,index)=>{const box=item.getBoundingClientRect(),current=Math.abs(box.left+box.width/2-center);if(current<distance){distance=current;active=index;}});items.forEach((item,index)=>item.classList.toggle('active',index===active));dotItems.forEach((dot,index)=>dot.classList.toggle('active',index===active));previous.disabled=active===0;next.disabled=active===items.length-1;};const scrollTo=(index,behavior='smooth')=>{const item=items[Math.max(0,Math.min(index,items.length-1))],left=item.offsetLeft-(viewport.clientWidth-item.offsetWidth)/2;viewport.scrollTo({left,behavior});};viewport.addEventListener('scroll',()=>{cancelAnimationFrame(frame);frame=requestAnimationFrame(markCentered);},{passive:true});previous.onclick=()=>{const active=items.findIndex(item=>item.classList.contains('active'));scrollTo(active-1);};next.onclick=()=>{const active=items.findIndex(item=>item.classList.contains('active'));scrollTo(active+1);};requestAnimationFrame(()=>{scrollTo(latestIndex,'auto');markCentered();});}
    function parseEmployeeDate(value){const text=String(value||'').trim();if(!text)return null;let match=text.match(/^(\d{4})[-/.](\d{1,2})[-/.](\d{1,2})$/),date;if(match)date=new Date(Number(match[1]),Number(match[2])-1,Number(match[3]));else if((match=text.match(/^(\d{1,2})[-/.](\d{1,2})[-/.](\d{4})$/)))date=new Date(Number(match[3]),Number(match[2])-1,Number(match[1]));else date=new Date(text);return Number.isNaN(date.getTime())?null:date;}
})();
