(() => {
    'use strict';
    const DB_NAME = 'birthday-studio', DB_VERSION = 2, OUTPUT_WIDTH = 1020, OUTPUT_HEIGHT = 1900, PHOTO_SIZE = 800, PHOTO_TOP_OFFSET = 110, TEMPLATE_COUNT = 27;
    const TEMPLATE_Y = [850,735,820,800,850,850,850,850,850,850,850,820,850,800,800,850,850,850,850,850,850,850,850,820,850,820,800];
    const elements = {}; let database, employees = [], employeePhotos = new Map(), photoObjectUrls = [], selectedEmployeeId = null, pendingWorkbook = null, pendingEmployees = [];
    document.addEventListener('DOMContentLoaded', initialize);

    async function initialize() {
        ['notice','newExcelButton','exportButton','importInput','uploadPanel','closeUploadButton','dropZone','excelInput','excelPreview','previewSummary','previewBody','processButton','nameFilter','locationFilter','employeeCount','employeeEmpty','employeeTableWrap','employeeBody','photoInput','editDialog','editForm','editClose','editCancel','editId','editName','editLocation','editEmail','editDob','editDoj'].forEach(id => elements[id] = document.getElementById(id));
        database = await openDatabase(); bindEvents(); await refreshEmployees();
    }
    function bindEvents() {
        elements.nameFilter.addEventListener('input', renderEmployees); elements.locationFilter.addEventListener('change', renderEmployees);
        elements.photoInput.addEventListener('change', () => uploadPhoto(elements.photoInput.files[0])); elements.editClose.addEventListener('click', () => elements.editDialog.close()); elements.editCancel.addEventListener('click', () => elements.editDialog.close()); elements.editForm.addEventListener('submit', saveEmployeeEdit);
        elements.newExcelButton.addEventListener('click',()=>{elements.uploadPanel.hidden=false;elements.excelInput.value='';}); elements.closeUploadButton.addEventListener('click',()=>elements.uploadPanel.hidden=true);
        elements.excelInput.addEventListener('change',()=>handleExcel(elements.excelInput.files[0])); elements.dropZone.addEventListener('dragover',event=>{event.preventDefault();elements.dropZone.classList.add('dragging');}); elements.dropZone.addEventListener('dragleave',()=>elements.dropZone.classList.remove('dragging')); elements.dropZone.addEventListener('drop',event=>{event.preventDefault();elements.dropZone.classList.remove('dragging');handleExcel(event.dataTransfer.files[0]);});
        elements.processButton.addEventListener('click',saveWorkbookAndEmployees); elements.exportButton.addEventListener('click',exportBackup); elements.importInput.addEventListener('change',()=>importBackup(elements.importInput.files[0]));
    }
    async function handleExcel(file){
        if(!file)return;if(!/\.(xlsx|xlsm)$/i.test(file.name)){showNotice('Please choose an XLSX or XLSM workbook.','error');return;}
        try{const buffer=await file.arrayBuffer(),workbook=XLSX.read(buffer,{type:'array',cellDates:true}),sheet=workbook.Sheets[workbook.SheetNames[0]],rows=XLSX.utils.sheet_to_json(sheet,{header:1,raw:false,dateNF:'yyyy-mm-dd',defval:''});validateHeaders(rows[0]||[]);const existing=new Set(employees.map(item=>normalize(item.id))),seen=new Set();pendingEmployees=rows.slice(1).map((row,index)=>createEmployee(row,index+2,existing,seen)).filter(Boolean);if(!pendingEmployees.length)throw new Error('No employee rows were found below the header.');pendingWorkbook={file,blob:new Blob([buffer],{type:file.type||'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'})};renderExcelPreview();}
        catch(error){pendingWorkbook=null;pendingEmployees=[];showNotice(error.message,'error');}
    }
    function validateHeaders(headers){const expected=[['employeeid','employee id','empid','emp id'],['fullname','full name','name'],['location'],['email','email address'],['dob','date of birth'],['doj','date of joining','joining date']];if(expected.some((accepted,index)=>!accepted.includes(normalize(headers[index]))))throw new Error('Invalid columns. Row 1 must be: A Employee ID, B Full Name, C Location, D Email, E DOB, F DOJ.');}
    function createEmployee(row,rowNumber,existing,seen){const id=String(row[0]||'').trim(),fullName=String(row[1]||'').trim();if(!id&&!fullName)return null;let status='New';if(!id||!fullName)status='Invalid: ID and name required';else if(existing.has(normalize(id)))status='Duplicate: already saved';else if(seen.has(normalize(id)))status='Duplicate ID in workbook';if(id)seen.add(normalize(id));return{id,fullName,location:String(row[2]||'').trim(),email:String(row[3]||'').trim(),dob:String(row[4]||'').trim(),doj:String(row[5]||'').trim(),photo:false,birthdayCard:false,createdAt:new Date().toISOString(),rowNumber,status};}
    function renderExcelPreview(){elements.previewBody.replaceChildren();pendingEmployees.slice(0,100).forEach(employee=>{const row=document.createElement('tr');[employee.id,employee.fullName,employee.location,employee.email,employee.dob,employee.doj,employee.status].forEach(value=>appendCell(row,value));elements.previewBody.appendChild(row);});const newCount=pendingEmployees.filter(item=>item.status==='New').length;elements.previewSummary.textContent=`${pendingWorkbook.file.name}: ${newCount} new employee(s), ${pendingEmployees.length-newCount} invalid or duplicate row(s).`;elements.processButton.disabled=newCount===0;elements.excelPreview.hidden=false;}
    async function saveWorkbookAndEmployees(){if(!pendingWorkbook)return;const valid=pendingEmployees.filter(item=>item.status==='New').map(({status,rowNumber,...employee})=>employee);try{const extension=pendingWorkbook.file.name.split('.').pop().toLowerCase(),savedName=`Employees_${timestamp()}.${extension}`;await put('files',{id:savedName,name:savedName,type:'workbook',blob:pendingWorkbook.blob,savedAt:new Date().toISOString()});for(const employee of valid)await put('employees',employee);showNotice(`Saved ${savedName} in browser storage and added ${valid.length} employee(s). ${pendingEmployees.length-valid.length} row(s) skipped.`,'success');pendingWorkbook=null;pendingEmployees=[];elements.excelInput.value='';elements.excelPreview.hidden=true;elements.uploadPanel.hidden=true;await refreshEmployees();}catch(error){showNotice(`Could not save the workbook: ${error.message}`,'error');}}
    function exportBackup(){const payload={version:1,exportedAt:new Date().toISOString(),employees};downloadBlob(new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),`BirthdayStudio_Backup_${timestamp()}.json`);}
    async function importBackup(file){if(!file)return;try{const payload=JSON.parse(await file.text());if(!Array.isArray(payload.employees))throw new Error('Backup does not contain an employees list.');for(const employee of payload.employees){if(employee.id&&employee.fullName)await put('employees',employee);}showNotice(`Imported ${payload.employees.length} employee record(s).`,'success');await refreshEmployees();}catch(error){showNotice(`Backup import failed: ${error.message}`,'error');}elements.importInput.value='';}
    async function refreshEmployees() { const [employeeRecords,photoRecords]=await Promise.all([getAll('employees'),getAll('photos')]); employees=employeeRecords.sort((a,b)=>a.fullName.localeCompare(b.fullName)); employeePhotos=new Map(photoRecords.map(photo=>[photo.id,photo])); renderLocationOptions(); renderEmployees(); }
    function renderLocationOptions() { const selected = elements.locationFilter.value; const locations = [...new Set(employees.map(item => item.location).filter(Boolean))].sort((a,b)=>a.localeCompare(b)); elements.locationFilter.replaceChildren(new Option('All locations','')); locations.forEach(location => elements.locationFilter.add(new Option(location,location))); if (locations.includes(selected)) elements.locationFilter.value = selected; }
    function renderEmployees() {
        const name = normalize(elements.nameFilter.value), location = elements.locationFilter.value; const visible = employees.filter(employee => normalize(employee.fullName).includes(name) && (!location || employee.location === location)); photoObjectUrls.forEach(URL.revokeObjectURL);photoObjectUrls=[];elements.employeeBody.replaceChildren();
        visible.forEach(employee => { const row = document.createElement('tr'); appendCell(row,employee.id); appendEmployeeNameCell(row,employee); appendCell(row,employee.email||'—'); appendCell(row,employee.dob||'—'); appendCell(row,employee.doj||'—'); appendAction(row,'Edit',()=>openEdit(employee)); appendAction(row,'Delete',()=>deleteEmployee(employee),'delete'); const cell=document.createElement('td'),button=document.createElement('button'); button.className='table-button photo-button'; button.type='button'; button.textContent=employee.photo?'Replace Photo':'Upload Photo'; button.addEventListener('click',()=>{selectedEmployeeId=employee.id;elements.photoInput.value='';elements.photoInput.click();}); cell.appendChild(button); if(employee.photo){const state=document.createElement('span');state.className='photo-state';state.textContent=employee.birthdayCard?'Card generated':'Photo saved';cell.appendChild(state);} row.appendChild(cell);elements.employeeBody.appendChild(row); });
        elements.employeeCount.textContent=`${visible.length} of ${employees.length} employee${employees.length===1?'':'s'}`; elements.employeeEmpty.hidden=employees.length>0; elements.employeeTableWrap.hidden=employees.length===0;
    }
    function openEdit(employee) { selectedEmployeeId=employee.id; elements.editId.value=employee.id; elements.editName.value=employee.fullName; elements.editLocation.value=employee.location||''; elements.editEmail.value=employee.email||''; elements.editDob.value=employee.dob||''; elements.editDoj.value=employee.doj||''; elements.editDialog.showModal(); }
    async function saveEmployeeEdit(event) { event.preventDefault(); const employee=employees.find(item=>item.id===selectedEmployeeId); if(!employee)return; employee.fullName=elements.editName.value.trim(); employee.location=elements.editLocation.value.trim(); employee.email=elements.editEmail.value.trim(); employee.dob=elements.editDob.value.trim(); employee.doj=elements.editDoj.value.trim(); employee.updatedAt=new Date().toISOString(); await put('employees',employee); const card=await get('cards',employee.id); if(card){card.fullName=employee.fullName;await put('cards',card);} elements.editDialog.close();showNotice(`Updated ${employee.fullName}.`,'success');await refreshEmployees(); }
    async function deleteEmployee(employee) { if(!confirm(`Delete ${employee.fullName} and their saved photo/card data?`))return; await Promise.all([remove('employees',employee.id),remove('photos',employee.id),remove('cards',employee.id)]); showNotice(`Deleted ${employee.fullName}.`,'success');await refreshEmployees(); }
    async function uploadPhoto(file) {
        if(!file||!selectedEmployeeId)return; const employee=employees.find(item=>item.id===selectedEmployeeId);if(!employee)return; if(!['image/png','image/jpeg','image/webp'].includes(file.type)){showNotice('Choose a PNG, JPG, JPEG, or WebP image.','error');return;}
        try { await loadImage(file); const extension=file.type==='image/png'?'png':file.type==='image/webp'?'webp':'jpg',photoName=`${safeFilename(employee.id)}_${safeFilename(employee.fullName)}.${extension}`; await put('photos',{id:employee.id,fileName:photoName,blob:file,savedAt:new Date().toISOString()}); employee.photo=true;employee.birthdayCard=false;employee.updatedAt=new Date().toISOString();await put('employees',employee); await generateAndSaveCard(employee,file);showNotice(`Photo saved in browser storage and birthday card created for ${employee.fullName}.`,'success');await refreshEmployees(); }
        catch(error){employee.photo=true;employee.birthdayCard=false;await put('employees',employee);showNotice(`Photo saved, but card generation failed: ${error.message}`,'error');await refreshEmployees();}
    }
    async function generateAndSaveCard(employee,photoBlob) {
        const templateNumber=Math.floor(Math.random()*TEMPLATE_COUNT)+1,template=await loadImage(readTemplateData(templateNumber)),photo=await loadImage(photoBlob),canvas=document.createElement('canvas');canvas.width=OUTPUT_WIDTH;canvas.height=OUTPUT_HEIGHT;const context=canvas.getContext('2d');context.drawImage(template,0,0,OUTPUT_WIDTH,OUTPUT_HEIGHT);const x=510-PHOTO_SIZE/2,y=Math.max(0,Math.min(TEMPLATE_Y[templateNumber-1]+PHOTO_TOP_OFFSET-PHOTO_SIZE/2,OUTPUT_HEIGHT-PHOTO_SIZE));context.save();context.beginPath();context.roundRect(x,y,PHOTO_SIZE,PHOTO_SIZE,80);context.clip();drawImageCover(context,photo,x,y,PHOTO_SIZE,PHOTO_SIZE);context.restore();const blob=await canvasToBlob(canvas),fileName=cardFileName(employee.fullName);await put('cards',{id:employee.id,employeeId:employee.id,fullName:employee.fullName,templateNumber,fileName,blob,createdAt:new Date().toISOString()});employee.birthdayCard=true;await put('employees',employee);
    }
    function readTemplateData(number){const source=window.BIRTHDAY_TEMPLATE_DATA?.[number];if(!source)throw new Error(`Embedded template ${number} is unavailable.`);return source;}
    function openDatabase(){return new Promise((resolve,reject)=>{const request=indexedDB.open(DB_NAME,DB_VERSION);request.onupgradeneeded=()=>{const db=request.result;['employees','photos','cards','files','certificates'].forEach(store=>{if(!db.objectStoreNames.contains(store))db.createObjectStore(store,{keyPath:'id'});});if(!db.objectStoreNames.contains('settings'))db.createObjectStore('settings',{keyPath:'key'});};request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);});}
    function storeRequest(store,mode,operation){return new Promise((resolve,reject)=>{const transaction=database.transaction(store,mode),request=operation(transaction.objectStore(store));request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);});}
    const put=(store,value)=>storeRequest(store,'readwrite',objectStore=>objectStore.put(value)),get=(store,key)=>storeRequest(store,'readonly',objectStore=>objectStore.get(key)),getAll=store=>storeRequest(store,'readonly',objectStore=>objectStore.getAll()),remove=(store,key)=>storeRequest(store,'readwrite',objectStore=>objectStore.delete(key));
    function appendEmployeeNameCell(row,employee){const cell=document.createElement('td'),profile=document.createElement('div'),avatar=document.createElement('div'),details=document.createElement('div'),name=document.createElement('strong'),location=document.createElement('small'),photo=employeePhotos.get(employee.id);cell.className='employee-name-cell';profile.className='employee-profile';avatar.className='employee-avatar';name.textContent=employee.fullName;location.textContent=employee.location||'Location not provided';if(photo?.blob){const image=document.createElement('img'),url=URL.createObjectURL(photo.blob);photoObjectUrls.push(url);image.src=url;image.alt='';avatar.appendChild(image);}else{avatar.textContent=getInitials(employee.fullName);avatar.setAttribute('aria-hidden','true');}details.className='employee-profile-text';details.append(name,location);profile.append(avatar,details);cell.appendChild(profile);row.appendChild(cell);}
    function getInitials(value){return String(value||'Employee').trim().split(/\s+/).slice(0,2).map(part=>part[0]?.toUpperCase()||'').join('')||'E';}
    function appendCell(row,value){const cell=document.createElement('td');cell.textContent=value;row.appendChild(cell);} function appendAction(row,label,handler,className=''){const cell=document.createElement('td'),button=document.createElement('button');button.type='button';button.className=`table-button ${className}`.trim();button.textContent=label;button.addEventListener('click',handler);cell.appendChild(button);row.appendChild(cell);}
    function showNotice(message,type){elements.notice.textContent=message;elements.notice.className=`notice ${type}`;elements.notice.hidden=false;} function normalize(value){return String(value||'').trim().toLowerCase().replace(/\s+/g,' ');} function safeFilename(value){return String(value||'Employee').replace(/[^A-Za-z0-9._ -]+/g,'').trim().replace(/\s+/g,'_')||'Employee';}
    function cardFileName(fullName){const readable=String(fullName||'Employee').replace(/[&_]+/g,' ').replace(/[<>:"/\\|?*\x00-\x1F]+/g,'').trim().replace(/\s+/g,' ')||'Employee';return `${readable}.jpg`;}
    function timestamp(){const date=new Date(),pad=value=>String(value).padStart(2,'0');return `${date.getFullYear()}${pad(date.getMonth()+1)}${pad(date.getDate())}_${pad(date.getHours())}${pad(date.getMinutes())}${pad(date.getSeconds())}`;} function downloadBlob(blob,fileName){const url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=fileName;document.body.appendChild(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
    function loadImage(source){return new Promise((resolve,reject)=>{const image=new Image(),url=source instanceof Blob?URL.createObjectURL(source):source;image.onload=()=>{if(source instanceof Blob)URL.revokeObjectURL(url);resolve(image);};image.onerror=()=>{if(source instanceof Blob)URL.revokeObjectURL(url);reject(new Error('The image could not be loaded.'));};image.src=url;});}
    function drawImageCover(context,image,x,y,width,height){const ratio=Math.max(width/image.naturalWidth,height/image.naturalHeight),drawWidth=image.naturalWidth*ratio,drawHeight=image.naturalHeight*ratio;context.drawImage(image,x+(width-drawWidth)/2,y+(height-drawHeight)/2,drawWidth,drawHeight);} function canvasToBlob(canvas){return new Promise((resolve,reject)=>canvas.toBlob(blob=>blob?resolve(blob):reject(new Error('The card could not be exported.')),'image/jpeg',.95));}
})();
